// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.14.0
// source: app.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ChannelAction int32

const (
	ChannelAction_Accept ChannelAction = 0
	ChannelAction_Denied ChannelAction = 1
)

// Enum value maps for ChannelAction.
var (
	ChannelAction_name = map[int32]string{
		0: "Accept",
		1: "Denied",
	}
	ChannelAction_value = map[string]int32{
		"Accept": 0,
		"Denied": 1,
	}
)

func (x ChannelAction) Enum() *ChannelAction {
	p := new(ChannelAction)
	*p = x
	return p
}

func (x ChannelAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelAction) Descriptor() protoreflect.EnumDescriptor {
	return file_app_proto_enumTypes[0].Descriptor()
}

func (ChannelAction) Type() protoreflect.EnumType {
	return &file_app_proto_enumTypes[0]
}

func (x ChannelAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelAction.Descriptor instead.
func (ChannelAction) EnumDescriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0}
}

type AppChannelReq_ChannelAction int32

const (
	AppChannelReq_Add    AppChannelReq_ChannelAction = 0
	AppChannelReq_Delete AppChannelReq_ChannelAction = 1
)

// Enum value maps for AppChannelReq_ChannelAction.
var (
	AppChannelReq_ChannelAction_name = map[int32]string{
		0: "Add",
		1: "Delete",
	}
	AppChannelReq_ChannelAction_value = map[string]int32{
		"Add":    0,
		"Delete": 1,
	}
)

func (x AppChannelReq_ChannelAction) Enum() *AppChannelReq_ChannelAction {
	p := new(AppChannelReq_ChannelAction)
	*p = x
	return p
}

func (x AppChannelReq_ChannelAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppChannelReq_ChannelAction) Descriptor() protoreflect.EnumDescriptor {
	return file_app_proto_enumTypes[1].Descriptor()
}

func (AppChannelReq_ChannelAction) Type() protoreflect.EnumType {
	return &file_app_proto_enumTypes[1]
}

func (x AppChannelReq_ChannelAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppChannelReq_ChannelAction.Descriptor instead.
func (AppChannelReq_ChannelAction) EnumDescriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0, 0}
}

type AppChannelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//	*AppChannelReq_Login_
	//	*AppChannelReq_Status
	//	*AppChannelReq_Channel
	Req isAppChannelReq_Req `protobuf_oneof:"req"`
}

func (x *AppChannelReq) Reset() {
	*x = AppChannelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppChannelReq) ProtoMessage() {}

func (x *AppChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppChannelReq.ProtoReflect.Descriptor instead.
func (*AppChannelReq) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0}
}

func (m *AppChannelReq) GetReq() isAppChannelReq_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *AppChannelReq) GetLogin() *AppChannelReq_Login {
	if x, ok := x.GetReq().(*AppChannelReq_Login_); ok {
		return x.Login
	}
	return nil
}

func (x *AppChannelReq) GetStatus() StatusType {
	if x, ok := x.GetReq().(*AppChannelReq_Status); ok {
		return x.Status
	}
	return StatusType_Online
}

func (x *AppChannelReq) GetChannel() *AppChannelReq_ChannelReq {
	if x, ok := x.GetReq().(*AppChannelReq_Channel); ok {
		return x.Channel
	}
	return nil
}

type isAppChannelReq_Req interface {
	isAppChannelReq_Req()
}

type AppChannelReq_Login_ struct {
	Login *AppChannelReq_Login `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type AppChannelReq_Status struct {
	Status StatusType `protobuf:"varint,2,opt,name=status,proto3,enum=api.proc.StatusType,oneof"`
}

type AppChannelReq_Channel struct {
	Channel *AppChannelReq_ChannelReq `protobuf:"bytes,3,opt,name=channel,proto3,oneof"`
}

func (*AppChannelReq_Login_) isAppChannelReq_Req() {}

func (*AppChannelReq_Status) isAppChannelReq_Req() {}

func (*AppChannelReq_Channel) isAppChannelReq_Req() {}

type Channel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Change string `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"`
}

func (x *Channel) Reset() {
	*x = Channel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{1}
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetChange() string {
	if x != nil {
		return x.Change
	}
	return ""
}

type ChannelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Action ChannelAction `protobuf:"varint,2,opt,name=action,proto3,enum=api.proc.ChannelAction" json:"action,omitempty"`
}

func (x *ChannelRes) Reset() {
	*x = ChannelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRes) ProtoMessage() {}

func (x *ChannelRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRes.ProtoReflect.Descriptor instead.
func (*ChannelRes) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelRes) GetAction() ChannelAction {
	if x != nil {
		return x.Action
	}
	return ChannelAction_Accept
}

type AppChannelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//	*AppChannelRes_Error
	//	*AppChannelRes_Channel
	//	*AppChannelRes_ReqRes
	Res isAppChannelRes_Res `protobuf_oneof:"res"`
}

func (x *AppChannelRes) Reset() {
	*x = AppChannelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppChannelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppChannelRes) ProtoMessage() {}

func (x *AppChannelRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppChannelRes.ProtoReflect.Descriptor instead.
func (*AppChannelRes) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{3}
}

func (m *AppChannelRes) GetRes() isAppChannelRes_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *AppChannelRes) GetError() string {
	if x, ok := x.GetRes().(*AppChannelRes_Error); ok {
		return x.Error
	}
	return ""
}

func (x *AppChannelRes) GetChannel() *Channel {
	if x, ok := x.GetRes().(*AppChannelRes_Channel); ok {
		return x.Channel
	}
	return nil
}

func (x *AppChannelRes) GetReqRes() *ChannelRes {
	if x, ok := x.GetRes().(*AppChannelRes_ReqRes); ok {
		return x.ReqRes
	}
	return nil
}

type isAppChannelRes_Res interface {
	isAppChannelRes_Res()
}

type AppChannelRes_Error struct {
	Error string `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type AppChannelRes_Channel struct {
	Channel *Channel `protobuf:"bytes,2,opt,name=channel,proto3,oneof"`
}

type AppChannelRes_ReqRes struct {
	ReqRes *ChannelRes `protobuf:"bytes,3,opt,name=reqRes,proto3,oneof"`
}

func (*AppChannelRes_Error) isAppChannelRes_Res() {}

func (*AppChannelRes_Channel) isAppChannelRes_Res() {}

func (*AppChannelRes_ReqRes) isAppChannelRes_Res() {}

type AppChannelReq_ChannelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Action AppChannelReq_ChannelAction `protobuf:"varint,2,opt,name=action,proto3,enum=api.proc.AppChannelReq_ChannelAction" json:"action,omitempty"`
}

func (x *AppChannelReq_ChannelReq) Reset() {
	*x = AppChannelReq_ChannelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppChannelReq_ChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppChannelReq_ChannelReq) ProtoMessage() {}

func (x *AppChannelReq_ChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppChannelReq_ChannelReq.ProtoReflect.Descriptor instead.
func (*AppChannelReq_ChannelReq) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AppChannelReq_ChannelReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppChannelReq_ChannelReq) GetAction() AppChannelReq_ChannelAction {
	if x != nil {
		return x.Action
	}
	return AppChannelReq_Add
}

type AppChannelReq_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AppChannelReq_Login) Reset() {
	*x = AppChannelReq_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppChannelReq_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppChannelReq_Login) ProtoMessage() {}

func (x *AppChannelReq_Login) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppChannelReq_Login.ProtoReflect.Descriptor instead.
func (*AppChannelReq_Login) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AppChannelReq_Login) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AppChannelReq_Login) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_app_proto protoreflect.FileDescriptor

var file_app_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x63, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x85, 0x03, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x35, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x41, 0x70,
	0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3e, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x41, 0x70, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x48,
	0x00, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x1a, 0x5f, 0x0a, 0x0a, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x41, 0x70, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x3f, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x24, 0x0a, 0x0d,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x64, 0x64, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x10, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x22, 0x35, 0x0a, 0x07, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x22, 0x51, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x8d, 0x01, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2d, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x48, 0x00, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x06,
	0x72, 0x65, 0x71, 0x52, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x71, 0x52, 0x65, 0x73, 0x42, 0x05, 0x0a, 0x03,
	0x72, 0x65, 0x73, 0x2a, 0x27, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x10, 0x01, 0x32, 0x4f, 0x0a, 0x0a,
	0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x63,
	0x2e, 0x41, 0x70, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x41, 0x70, 0x70, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x07, 0x5a,
	0x05, 0x2e, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_proto_rawDescOnce sync.Once
	file_app_proto_rawDescData = file_app_proto_rawDesc
)

func file_app_proto_rawDescGZIP() []byte {
	file_app_proto_rawDescOnce.Do(func() {
		file_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_proto_rawDescData)
	})
	return file_app_proto_rawDescData
}

var file_app_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_app_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_proto_goTypes = []interface{}{
	(ChannelAction)(0),               // 0: api.proc.ChannelAction
	(AppChannelReq_ChannelAction)(0), // 1: api.proc.AppChannelReq.ChannelAction
	(*AppChannelReq)(nil),            // 2: api.proc.AppChannelReq
	(*Channel)(nil),                  // 3: api.proc.Channel
	(*ChannelRes)(nil),               // 4: api.proc.ChannelRes
	(*AppChannelRes)(nil),            // 5: api.proc.AppChannelRes
	(*AppChannelReq_ChannelReq)(nil), // 6: api.proc.AppChannelReq.ChannelReq
	(*AppChannelReq_Login)(nil),      // 7: api.proc.AppChannelReq.Login
	(StatusType)(0),                  // 8: api.proc.StatusType
}
var file_app_proto_depIdxs = []int32{
	7, // 0: api.proc.AppChannelReq.login:type_name -> api.proc.AppChannelReq.Login
	8, // 1: api.proc.AppChannelReq.status:type_name -> api.proc.StatusType
	6, // 2: api.proc.AppChannelReq.channel:type_name -> api.proc.AppChannelReq.ChannelReq
	0, // 3: api.proc.ChannelRes.action:type_name -> api.proc.ChannelAction
	3, // 4: api.proc.AppChannelRes.channel:type_name -> api.proc.Channel
	4, // 5: api.proc.AppChannelRes.reqRes:type_name -> api.proc.ChannelRes
	1, // 6: api.proc.AppChannelReq.ChannelReq.action:type_name -> api.proc.AppChannelReq.ChannelAction
	2, // 7: api.proc.AppService.Channel:input_type -> api.proc.AppChannelReq
	5, // 8: api.proc.AppService.Channel:output_type -> api.proc.AppChannelRes
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_app_proto_init() }
func file_app_proto_init() {
	if File_app_proto != nil {
		return
	}
	file_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppChannelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Channel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppChannelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppChannelReq_ChannelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppChannelReq_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AppChannelReq_Login_)(nil),
		(*AppChannelReq_Status)(nil),
		(*AppChannelReq_Channel)(nil),
	}
	file_app_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*AppChannelRes_Error)(nil),
		(*AppChannelRes_Channel)(nil),
		(*AppChannelRes_ReqRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_proto_goTypes,
		DependencyIndexes: file_app_proto_depIdxs,
		EnumInfos:         file_app_proto_enumTypes,
		MessageInfos:      file_app_proto_msgTypes,
	}.Build()
	File_app_proto = out.File
	file_app_proto_rawDesc = nil
	file_app_proto_goTypes = nil
	file_app_proto_depIdxs = nil
}
